name: ui_kit
description: "A new Flutter package project."
version: 0.0.1
# homepage:

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.20.2
  widgetbook_annotation: ^3.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  widgetbook_generator: ^3.20.1
  build_runner: ^2.10.4
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/fonts/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
fonts:
  - family: SF-Pro
    fonts:
      - asset: assets/fonts/SF-Pro-Display-Bold.otf
        weight: 700
      - asset: assets/fonts/SF-Pro-Display-Heavy.otf
        weight: 800
      - asset: assets/fonts/SF-Pro-Display-Medium.otf
        weight: 500
      - asset: assets/fonts/SF-Pro-Display-Regular.otf
        weight: 400
      - asset: assets/fonts/SF-Pro-Display-Semibold.otf
        weight: 600
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
