name: widgetbook
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  widgetbook_annotation: ^3.9.0
  widgetbook: ^3.20.2
  language_app:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner:
  widgetbook_generator: ^3.20.1

flutter:
  uses-material-design: true
